### ISSUE TITLE
Contact methods + Translation Guide

### ISSUE THREAD

**Issue by jermanuts** [saturneric/GpgFrontend-Manual#2]
Are there plans to add other contact methods like a [matrix ](https://matrix.org/) room for a more active community and instant messaging?

The switch to Qt translation made it hard to find the original (English) strings, so translators can edit it out and add a new locale. Can't find it [here](https://github.com/saturneric/GpgFrontend/tree/main/resource/lfs/locale/ts).

EDIT: Shouldn't the app logo be 
![image](https://github.com/saturneric/GpgFrontend-Manual/assets/109705802/8bba36fa-8b07-46c3-aafd-26aa4ab8ea83)

instead of

![image](https://github.com/saturneric/GpgFrontend-Manual/assets/109705802/373fc269-6178-450d-8874-4f97099da85d)
?

**Comment by saturneric** [comment]
The new icon was created after the binary release of v2.1.2. Therefore, in v2.1.3, all the binary release will switch to the new icon.

Currently, the flatpak release is using the new icon.

**Comment by saturneric** [comment]
@jermanuts  In my opinion, the value of the OpenPGP and mail is decentralized, which means you can easily switch to another channel with the same communication protocol. However, there are gradually getting out of the modern style. I am currently thinking, is there a way to send instant message without registering an account, or can users build up their own server easily? If there is one, adding it to this app will certainly be considered.

**Comment by saturneric** [comment]
About the Qt Translation. I was making this decision (use Qt Translation System instead of gettext), under the consideration of the cross-platform stability and reducing thridparty dependencies. I think that currently it works fine. Here are some tipps may help:

1. Use Qt Linguist: This tool is designed for translating .ts files and offers a user-friendly interface for viewing and editing translations.
2. Check .ts Files: Ensure all strings needing translation are included in your .ts files. If any are missing, rerun the lupdate tool to update these files.
4. Manage Strings in Source Code: Make sure to appropriately mark all translatable strings with the tr() function in your source code to ensure they are captured by the lupdate tool.

**Comment by jermanuts** [comment]
>is there a way to send instant message without registering an account, or can users build up their own server easily?

You mean for community communications? You can [register on a homeserver](https://servers.joinmatrix.org/) that doesn't ask for an account but as you might guess, it won't be as reliable as if you were the one actually selfhosting it. So, you will have to register at matrix.org homeserver as a backup incase the homesever you chose is down or gone.

**Comment by jermanuts** [comment]
>use Qt Translation System

Yeah, but where is the source strings in the source code? So I can add in the docs for the translators to edit out.

**Comment by saturneric** [comment]
> > use Qt Translation System
> 
> Yeah, but where is the source strings in the source code? So I can add in the docs for the translators to edit out.

For example:

<img width="1165" alt="image" src="https://github.com/saturneric/GpgFrontend-Manual/assets/20257134/3545e968-5c99-42df-8812-0690b8e3dddc">

And then

<img width="1101" alt="image" src="https://github.com/saturneric/GpgFrontend-Manual/assets/20257134/ee1700f5-2767-4c2a-bbe3-c2a32f7df862">
